# GolangCI-Lint configuration for extendable-kubernetes-mcp-server
# Ensures clean, maintainable code that follows Go best practices

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional useful linters
    - bodyclose
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - lll
    - misspell
    - unconvert
    - unparam

  settings:
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    lll:
      line-length: 160
    misspell:
      locale: US

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - goconst
          - lll
          - gosec

      # Exclude shadow checking for err variables (common pattern)
      - text: "shadow: declaration of \"err\""
        linters:
          - govet

issues:
  max-issues-per-linter: 0
  max-same-issues: 0